### ISSUE TITLE
Unreadable reversed text overlays

### ISSUE THREAD

**Issue by timbertson** [ender-js/website#12]
Just thought you should know the site is pretty much unreadable in chromium 25.0.1364.172 on fedora 18:

![screenshot](https://f.cloud.github.com/assets/14172/499135/a19975f8-bc2e-11e2-8159-4c48f365b975.png)

**Comment by rvagg** [comment]
You're just not trying **hard enough** to read it obviously!

We heard of a very similar report on Twitter and it was solved by switching video drivers to the official ones (I can't remember if it was ATI or NVIDIA).

I'll have a look when I have a moment, perhaps we'll have to make it less hipster and remove the 3D transforms.

**Comment by efleming969** [comment]
Having same problem with Chromium 26.0.1410.63 on Arch.  Firefox is rendering fine.

**Comment by calvinmetcalf** [comment]
same issue with chrome 27.0.1453.116 on Windows 7

**Comment by rvagg** [comment]
someone want to volunteer to remove the 3d crap from the website? a simple css transition fade-in, fade-out would be fine.
