### ISSUE TITLE
Crazy scrolling in Safari

### ISSUE THREAD

**Issue by stephenmathieson** [ender-js/website#15]
Steps to reproduce:
1. open http://ender.jit.su in safari
2. scroll down until the "sticky" nav bar appears; the farther you scroll, the crazier the bug gets
3. click "news"
4. have seizure

**Comment by ded** [comment]
why would we ever fix this? like why?

**Comment by stephenmathieson** [comment]
i donno, maybe you shouldn't.  if you choose not to, i'd suggest fixing for all other browsers.  not only safari users should get this awesome experience. :p

**Comment by ded** [comment]
ah man. too late. i already fixed it. :frowning:
